# Generated by Django 4.1.7 on 2023-03-28 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='obra',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL),
        ),
    ]
