# Generated by Django 4.1.7 on 2023-03-30 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obras', '0005_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='obras', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='subtitulo',
            field=models.CharField(max_length=50, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Obra'),
        ),
    ]
