# Generated by Django 4.1.7 on 2023-03-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0007_obra_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
